package database

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"

	sqlitevec "github.com/asg017/sqlite-vec-go-bindings/cgo"
)

var migrationSQLiteExtensions sync.Once

func registerMigrationSQLiteExtensions() { migrationSQLiteExtensions.Do(sqlitevec.Auto) }

func generateSQLiteRuntimeProfiles(
	ctx context.Context,
	initialize func(
		string,
		int,
	) error,
) (
	map[string]schemaObjects,
	error,
) {
	profiles := map[string]schemaObjects{"base": {}, "fts": {}, "vector": {}}
	for _, dimension := range []int{0, 3} {
		file, err := os.CreateTemp("", "weknora-runtime-profile-*.sqlite")
		if err != nil {
			return nil, err
		}
		_ = file.Close()
		defer func() { _ = os.Remove(file.Name()) }()
		if err := initialize(file.Name(), dimension); err != nil {
			return nil, err
		}
		m, err := openMigrationConnection(
			ctx,
			"sqlite3://runtime-profile",
			MigrationOptions{SQLiteDBPath: file.Name()},
			true,
		)
		if err != nil {
			return nil, err
		}
		objects, tables, err := describeSchema(ctx, m.conn, "sqlite")
		m.close()
		if err != nil {
			return nil, err
		}
		if !tables["lite_embeddings"] || !tables["lite_embeddings_fts"] {
			return nil, fmt.Errorf("runtime profile generation requires the actual retriever with " + "sqlite_fts5")
		}
		for key, value := range objects {
			table := tableOfObject(key)
			if dimension == 0 {
				if table == "lite_embeddings" {
					profiles["base"][key] = value
				} else if strings.HasPrefix(table, "lite_embeddings_fts") {
					profiles["fts"][key] = value
				} else {
					return nil, fmt.Errorf("unexpected runtime profile object %s", key)
				}
			}
			if dimension == 3 && strings.HasPrefix(table, "vec_embeddings_3") {
				key = strings.ReplaceAll(key, "vec_embeddings_3", "vec_embeddings_{dimension}")
				value = strings.ReplaceAll(value, "vec_embeddings_3", "vec_embeddings_{dimension}")
				value = strings.ReplaceAll(value, "float[3]", "float[{dimension}]")
				profiles["vector"][key] = value
			}
		}
	}
	if len(profiles["vector"]) == 0 {
		return nil, fmt.Errorf("runtime profile has no actual vec0 objects")
	}
	return profiles, nil
}

var runtimeVectorRoot = regexp.MustCompile(`^vec_embeddings_([1-9][0-9]*)$`)

// Runtime objects are optional groups. Every object in a present group must
// match the structures generated by the actual retriever. Unrecognized tables
// and extra objects remain in the migration comparison and fail closed.
func validateSQLiteRuntimeObjects(
	objects schemaObjects,
	tables map[string]bool,
	profiles map[string]schemaObjects,
) error {
	validateGroup := func(expected schemaObjects) error {
		if len(expected) == 0 {
			return fmt.Errorf("SQLite runtime reference is missing")
		}
		for key, value := range expected {
			if actual, ok := objects[key]; !ok || actual != value {
				return fmt.Errorf("SQLite runtime structure mismatch: %s", key)
			}
		}
		for key := range expected {
			delete(objects, key)
		}
		return nil
	}
	if tables["lite_embeddings"] {
		if err := validateGroup(profiles["base"]); err != nil {
			return err
		}
	}
	if tables["lite_embeddings_fts"] {
		if !tables["lite_embeddings"] {
			return fmt.Errorf("SQLite FTS runtime has no metadata table")
		}
		if err := validateGroup(profiles["fts"]); err != nil {
			return err
		}
	}
	for table := range tables {
		match := runtimeVectorRoot.FindStringSubmatch(table)
		if match == nil {
			continue
		}
		dimension, err := strconv.Atoi(match[1])
		if err != nil || dimension <= 0 || dimension > 8192 {
			return fmt.Errorf("unsupported SQLite runtime vector dimension")
		}
		if !tables["lite_embeddings"] {
			return fmt.Errorf("SQLite vector runtime has no metadata table")
		}
		expected := schemaObjects{}
		for key, value := range profiles["vector"] {
			expected[strings.ReplaceAll(key, "{dimension}", match[1])] = strings.ReplaceAll(
				value, "{dimension}", match[1],
			)
		}
		if err := validateGroup(expected); err != nil {
			return err
		}
	}
	return nil
}
