version: 2
linters-settings:
  lll:
    line-length: 120
    tab-width: 4
linters:
  enable:
    - lll
    - govet
    - revive
  exclusions:
    rules:
      - path: docs/docs\.go
        linters:
          - lll
formatters:
  enable:
    - gofmt
    - gofumpt
