ALTER TABLE model_usages ADD COLUMN IF NOT EXISTS status VARCHAR(16) NOT NULL DEFAULT 'success';
ALTER TABLE model_usages ADD COLUMN IF NOT EXISTS error_message VARCHAR(512) NOT NULL DEFAULT '';
ALTER TABLE model_usages ADD COLUMN IF NOT EXISTS duration_ms BIGINT NOT NULL DEFAULT 0;
