package contentkey

import (
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"golang.org/x/text/unicode/norm"
)

const (
	// ChunkNormalizationVersion identifies the exact text-normalization
	// contract used by ChunkContentDigest.
	ChunkNormalizationVersion = "chunk-normalization-v1"

	// ChunkIdentityVersion identifies the canonical field set and encoding used
	// by StableChunkID.
	ChunkIdentityVersion = "chunk-identity-v1"
)

// stableChunkNamespace isolates WeKnora chunk identities from UUIDv5 values
// generated by other applications or for other resource types.
var stableChunkNamespace = uuid.MustParse("427950d4-3432-5b1f-9c3c-58d60a466834")

// StableChunkIdentity contains the complete material for one deterministic
// ingestion chunk identity.
//
// ChunkType is a string rather than types.ChunkType because that repository
// type is an alias of string and this low-level package should not depend on
// the broad internal/types package. Callers can pass a types.ChunkType value
// without conversion.
type StableChunkIdentity struct {
	TenantID             uint64
	KnowledgeID          string
	ChunkType            string
	ParentIdentity       string
	ContentDigest        string
	ContextDigest        string
	DuplicateOrdinal     int
	NormalizationVersion string
	IdentityVersion      string
}

// ChunkCandidate contains the parser output needed to assign a stable chunk
// identity before database rows and their random IDs are created.
type ChunkCandidate struct {
	ChunkType     string
	Content       string
	ContextHeader string
	ParentIndex   int
}

// AssignedChunkIdentity is the stable identity assigned to one candidate.
type AssignedChunkIdentity struct {
	StableIdentity  string
	IdentityVersion string
}

// NormalizeChunkContent applies the chunk-normalization-v1 contract.
func NormalizeChunkContent(content string) string {
	content = strings.ReplaceAll(content, "\r\n", "\n")
	content = strings.ReplaceAll(content, "\r", "\n")
	content = norm.NFC.String(content)
	return strings.TrimSpace(content)
}

// ChunkContentDigest returns the lowercase SHA-256 digest of normalized
// content. The digest is an identity input, not a database row ID.
func ChunkContentDigest(content string) string {
	digest := sha256.Sum256([]byte(NormalizeChunkContent(content)))
	return hex.EncodeToString(digest[:])
}

// StableChunkID returns a deterministic RFC 4122 UUIDv5 for input.
//
// Every variable-length field is length-prefixed, and numeric fields use
// fixed-width big-endian encoding. This makes field boundaries unambiguous.
func StableChunkID(input StableChunkIdentity) string {
	return uuid.NewSHA1(stableChunkNamespace, encodeStableChunkIdentity(input)).String()
}

// AssignDuplicateOrdinals returns a copy of inputs with ordinals assigned in
// document order within each equal identity base. An identity base contains
// every identity field except DuplicateOrdinal.
func AssignDuplicateOrdinals(inputs []StableChunkIdentity) []StableChunkIdentity {
	result := make([]StableChunkIdentity, len(inputs))
	counts := make(map[string]int, len(inputs))

	for i, input := range inputs {
		baseKey := string(encodeStableChunkIdentityBase(input))
		input.DuplicateOrdinal = counts[baseKey]
		counts[baseKey]++
		result[i] = input
	}

	return result
}

// AssignChunkIdentities assigns parents first and then children in document
// order. A child with ParentIndex >= 0 includes the corresponding stable parent
// ID; a flat chunk uses ParentIndex < 0 and an empty parent identity.
func AssignChunkIdentities(
	tenantID uint64,
	knowledgeID string,
	parents []ChunkCandidate,
	children []ChunkCandidate,
) ([]AssignedChunkIdentity, []AssignedChunkIdentity, error) {
	parentMaterials := make([]StableChunkIdentity, len(parents))
	for i, parent := range parents {
		parentMaterials[i] = stableIdentityMaterial(
			tenantID,
			knowledgeID,
			parent,
			"",
		)
	}
	assignedParentMaterials := AssignDuplicateOrdinals(parentMaterials)
	assignedParents := assignedIdentities(assignedParentMaterials)

	childMaterials := make([]StableChunkIdentity, len(children))
	for i, child := range children {
		parentIdentity := ""
		if child.ParentIndex >= 0 {
			if child.ParentIndex >= len(assignedParents) {
				return nil, nil, fmt.Errorf(
					"child %d references parent index %d, but only %d parents exist",
					i,
					child.ParentIndex,
					len(assignedParents),
				)
			}
			parentIdentity = assignedParents[child.ParentIndex].StableIdentity
		}
		childMaterials[i] = stableIdentityMaterial(
			tenantID,
			knowledgeID,
			child,
			parentIdentity,
		)
	}

	return assignedParents, assignedIdentities(AssignDuplicateOrdinals(childMaterials)), nil
}

func stableIdentityMaterial(
	tenantID uint64,
	knowledgeID string,
	candidate ChunkCandidate,
	parentIdentity string,
) StableChunkIdentity {
	contextDigest := ""
	if candidate.ContextHeader != "" {
		contextDigest = ChunkContentDigest(candidate.ContextHeader)
	}
	return StableChunkIdentity{
		TenantID:             tenantID,
		KnowledgeID:          knowledgeID,
		ChunkType:            candidate.ChunkType,
		ParentIdentity:       parentIdentity,
		ContentDigest:        ChunkContentDigest(candidate.Content),
		ContextDigest:        contextDigest,
		NormalizationVersion: ChunkNormalizationVersion,
		IdentityVersion:      ChunkIdentityVersion,
	}
}

func assignedIdentities(inputs []StableChunkIdentity) []AssignedChunkIdentity {
	result := make([]AssignedChunkIdentity, len(inputs))
	for i, input := range inputs {
		result[i] = AssignedChunkIdentity{
			StableIdentity:  StableChunkID(input),
			IdentityVersion: input.IdentityVersion,
		}
	}
	return result
}

func encodeStableChunkIdentity(input StableChunkIdentity) []byte {
	encoded := encodeStableChunkIdentityBase(input)
	return appendInt64(encoded, int64(input.DuplicateOrdinal))
}

func encodeStableChunkIdentityBase(input StableChunkIdentity) []byte {
	encoded := make([]byte, 0, 256)
	encoded = appendString(encoded, input.IdentityVersion)
	encoded = appendString(encoded, input.NormalizationVersion)
	encoded = appendUint64(encoded, input.TenantID)
	encoded = appendString(encoded, input.KnowledgeID)
	encoded = appendString(encoded, input.ChunkType)
	encoded = appendString(encoded, input.ParentIdentity)
	encoded = appendString(encoded, input.ContentDigest)
	encoded = appendString(encoded, input.ContextDigest)
	return encoded
}

func appendString(dst []byte, value string) []byte {
	dst = appendUint64(dst, uint64(len(value)))
	return append(dst, value...)
}

func appendUint64(dst []byte, value uint64) []byte {
	var encoded [8]byte
	binary.BigEndian.PutUint64(encoded[:], value)
	return append(dst, encoded[:]...)
}

func appendInt64(dst []byte, value int64) []byte {
	return appendUint64(dst, uint64(value))
}
