package config

import (
	"testing"

	"github.com/Tencent/WeKnora/internal/types"
)

func TestSanitizeUnresolvedPlaceholders_ClearsLiteralEnvTokens(t *testing.T) {
	cfg := &Config{
		ParserDefaults: &ParserDefaultsConfig{
			MinerU: &MinerUDefaults{
				Endpoint:     "${MINERU_ENDPOINT}",
				Model:        "pipeline",
				VLMServerURL: "${MINERU_VLM_SERVER_URL}",
				Language:     "",
			},
			MinerUCloud: &MinerUCloudDefaults{
				APIKey:   "${MINERU_API_KEY}",
				Model:    "vlm",
				Language: "${MINERU_CLOUD_LANGUAGE}",
			},
		},
		StorageDefaults: &StorageDefaultsConfig{
			DefaultProvider: "${STORAGE_DEFAULT_PROVIDER}",
			MinIO: &types.MinIOEngineConfig{
				Endpoint:        "${MINIO_ENDPOINT}",
				AccessKeyID:     "minioadmin",
				SecretAccessKey: "${MINIO_SECRET_ACCESS_KEY}",
				BucketName:      "weknora-bucket",
			},
			S3: &types.S3EngineConfig{
				Region:    "${S3_REGION}",
				AccessKey: "AKIA...",
			},
		},
	}

	sanitizeUnresolvedPlaceholders(cfg)

	// Parser defaults: literal placeholders should be cleared, real values kept.
	if got := cfg.ParserDefaults.MinerU.Endpoint; got != "" {
		t.Errorf("MinerU.Endpoint = %q, want cleared", got)
	}
	if got := cfg.ParserDefaults.MinerU.Model; got != "pipeline" {
		t.Errorf("MinerU.Model = %q, want preserved real value 'pipeline'", got)
	}
	if got := cfg.ParserDefaults.MinerU.VLMServerURL; got != "" {
		t.Errorf("MinerU.VLMServerURL = %q, want cleared", got)
	}
	if got := cfg.ParserDefaults.MinerUCloud.APIKey; got != "" {
		t.Errorf("MinerUCloud.APIKey = %q, want cleared", got)
	}
	if got := cfg.ParserDefaults.MinerUCloud.Model; got != "vlm" {
		t.Errorf("MinerUCloud.Model = %q, want preserved", got)
	}
	if got := cfg.ParserDefaults.MinerUCloud.Language; got != "" {
		t.Errorf("MinerUCloud.Language = %q, want cleared", got)
	}

	// Storage defaults: same treatment.
	if got := cfg.StorageDefaults.DefaultProvider; got != "" {
		t.Errorf("DefaultProvider = %q, want cleared", got)
	}
	if got := cfg.StorageDefaults.MinIO.Endpoint; got != "" {
		t.Errorf("MinIO.Endpoint = %q, want cleared", got)
	}
	if got := cfg.StorageDefaults.MinIO.AccessKeyID; got != "minioadmin" {
		t.Errorf("MinIO.AccessKeyID = %q, want preserved", got)
	}
	if got := cfg.StorageDefaults.MinIO.SecretAccessKey; got != "" {
		t.Errorf("MinIO.SecretAccessKey = %q, want cleared", got)
	}
	if got := cfg.StorageDefaults.MinIO.BucketName; got != "weknora-bucket" {
		t.Errorf("MinIO.BucketName = %q, want preserved", got)
	}
	if got := cfg.StorageDefaults.S3.Region; got != "" {
		t.Errorf("S3.Region = %q, want cleared", got)
	}
	if got := cfg.StorageDefaults.S3.AccessKey; got != "AKIA..." {
		t.Errorf("S3.AccessKey = %q, want preserved", got)
	}
}

func TestSanitizeUnresolvedPlaceholders_NilSafe(t *testing.T) {
	// All nil paths exercised in one call.
	sanitizeUnresolvedPlaceholders(nil)
	sanitizeUnresolvedPlaceholders(&Config{})
	sanitizeUnresolvedPlaceholders(&Config{
		ParserDefaults:  &ParserDefaultsConfig{},
		StorageDefaults: &StorageDefaultsConfig{},
	})
}

func TestUnresolvedPlaceholderPattern_OnlyMatchesEnvLiterals(t *testing.T) {
	tests := []struct {
		in   string
		want bool
	}{
		{"${FOO}", true},
		{"${MINERU_ENDPOINT}", true},
		{"${ABC_123_DEF}", true},
		{"", false},
		{"plain value", false},
		{"prefix${FOO}", false},          // partial substitution is not our concern
		{"${foo}", false},                // lowercase isn't generated by our pattern
		{"http://${FOO}/bar", false},
		{"$FOO", false},
	}
	for _, tc := range tests {
		if got := unresolvedPlaceholderPattern.MatchString(tc.in); got != tc.want {
			t.Errorf("pattern.MatchString(%q) = %v, want %v", tc.in, got, tc.want)
		}
	}
}

func TestSnapshot_StoreAndLoad(t *testing.T) {
	// Capture previous value to restore for test isolation.
	prev := snapshotPtr.Load()
	t.Cleanup(func() {
		if prev == nil {
			snapshotPtr.Store(nil)
		} else {
			snapshotPtr.Store(prev)
		}
	})

	cfg := &Config{
		StorageDefaults: &StorageDefaultsConfig{DefaultProvider: "minio"},
	}
	storeSnapshot(cfg)
	got := Snapshot()
	if got != cfg {
		t.Fatalf("Snapshot() returned %p, want %p", got, cfg)
	}
	if got.StorageDefaults.DefaultProvider != "minio" {
		t.Errorf("Snapshot.StorageDefaults.DefaultProvider = %q, want minio",
			got.StorageDefaults.DefaultProvider)
	}
}

func TestSnapshot_NilStoreIgnored(t *testing.T) {
	prev := snapshotPtr.Load()
	t.Cleanup(func() {
		if prev == nil {
			snapshotPtr.Store(nil)
		} else {
			snapshotPtr.Store(prev)
		}
	})

	sentinel := &Config{}
	snapshotPtr.Store(sentinel)
	storeSnapshot(nil)
	if got := Snapshot(); got != sentinel {
		t.Errorf("storeSnapshot(nil) clobbered previous snapshot")
	}
}
